### ISSUE TITLE
kbs, mbc 동영상 정보 살리기

### ISSUE THREAD

**Issue by disjukr** [disjukr/just-news#1]
## 예시
- kbs: http://news.kbs.co.kr/news/NewsView.do?SEARCH_NEWS_CODE=2922636
- mbc: http://imnews.imbc.com/replay/2014/nwdesk/article/3522010_13490.html

**Comment by disjukr** [comment]
현상금 2만원 걸겠습니다. PR날릴 때 계좌번호 써주세요

**Comment by item4** [comment]
http://news.kbs.co.kr/news/NewsView.do?SEARCH_PAGE_NO=&SEARCH_NEWS_CODE=3078011&jews=false

**Comment by yous** [comment]
아직 MBC 동영상 정보 이슈는 남아있는 건가요?

**Comment by disjukr** [comment]
@yous 그런 것 같네요. 이슈 분리하겠습니다.
