### ISSUE TITLE
주간 경향 동작 안함

### ISSUE THREAD

**Issue by lexifdev** [disjukr/just-news#241]
참고 페이지
http://weekly.khan.co.kr/khnm.html?mode=view&code=116&artid=201602231430331&pt=nv

**Comment by disjukr** [comment]
딱히 에러가 발생하지 않는 것으로 보아 일단 https://github.com/disjukr/jews/blob/master/src%2Fjews.user.js#L88-L97 이 부분이 문제겠군여 ㄹㄹ

**Comment by lexifdev** [comment]
그냥 https://github.com/disjukr/jews/blob/master/src/sites.js 안에 weekly.khan.co.kr 가 없어 보입니다.
기존 경향 처리기 중 호환되는 녀석이 있는지는 확인해 볼 필요가 있겠습니다.

**Comment by disjukr** [comment]
아아 그렇군요
