### ISSUE TITLE
SBS 영상처리 문제 + (2019-02-22 현재 SBS에서 작동 안하는 문제도 해결 필요)

### ISSUE THREAD

**Issue by item4** [disjukr/just-news#248]
<img width="635" alt="2016-05-14 9 22 30" src="https://cloud.githubusercontent.com/assets/559952/15268452/24adfed6-1a1a-11e6-8ce2-b84d22f92ed9.png">

기사에 영상이 첨부되있는데, 컨트롤러만 나오고 영상은 안보입니다. 영상 element가 지워지진 않았는지 소리는 나옵니다.

http://news.sbs.co.kr/news/endPage.do?news_id=N1003571126

> 💰 이 이슈에는 현상금이 걸려있습니다.
> PR에 계좌번호(또는 토스계정)를 같이 적어주시면 `master` 브랜치에 머지될 때에 입금해드립니다.
> `20,000₩` backed by @d3m3vilurr

**Comment by teslamint** [comment]
사파리에서 1월 17일자 버전을 쓰고 있는데 얘는 잘 나오네요

**Comment by item4** [comment]
크롬으로 2016-06-07 쓰는데 화면이 좀 작긴 하지만 나옵니다.
Firefox에선 안나오네요.
Mac OS X 10.11.5 Firefox 47.0

**Comment by Beingbook** [comment]
윈도우 10에서 크롬, 파이어폭스 모두 재현이 안되네요...

**Comment by disjukr** [comment]
@Beingbook
좀 오래된 이슈라, 이슈가 올라올 당시에는 뭔가 처리는 되었으나 일부 내용만 보이지 않는 문제가 있었습니다.
지금은 아예 작동하지 않습니다.
SBS 처리를 새로 추가해야하는 일과 같습니다.

**Comment by Beingbook** [comment]
아 그렇군요. 사이트가 개편되면서 새로이 해야 되는 이슈군요.

**Comment by Beingbook** [comment]
이거 소제목 달린 뉴스링크 있을까요? 꽤나 찾아봤는데 소제목있는 기사를 못찾겠네요;;

**Comment by disjukr** [comment]
@Beingbook 소재목 없는 사이트는 구현을 안하면 됩니다.

**Comment by disjukr** [comment]
fixed from #316
