### ISSUE TITLE
서울신문 no title, 잘못된 작성일

### ISSUE THREAD

**Issue by disjukr** [disjukr/just-news#276]
http://www.seoul.co.kr/news/newsView.php?id=20170617500020

![2017-06-17 6 30 28](https://user-images.githubusercontent.com/690661/27251847-141e8d50-538b-11e7-926c-b20f0a907184.png)

**Comment by teslamint** [comment]
`2017-09-26` 버전에서 잘 나오네요.

![Screenshot](https://user-images.githubusercontent.com/158752/30898103-7b74f2ba-a394-11e7-822f-3e0222a1fdea.png)
