### ISSUE TITLE
타입스크립트로 재작성

### ISSUE THREAD

**Issue by disjukr** [disjukr/just-news#282]
두둥

**Comment by disjukr** [comment]
`--allowJs` 옵션으로 점진적 포팅 가능

**Comment by item4** [comment]
예시를 몇개 만들어주시면 따라하기 쉽지 않을까요

**Comment by disjukr** [comment]
@item4 작업중이에요

**Comment by disjukr** [comment]
예시: https://github.com/disjukr/just-news/blob/master/src/impl/ITWORLD.ts

**Comment by heejongahn** [comment]
NOGADA
