### ISSUE TITLE
아이티클 지원하기

### ISSUE THREAD

**Issue by disjukr** [disjukr/just-news#297]
http://www.itcle.com/2018/11/04/%ED%98%B8%EC%A3%BC-%EC%A0%95%EB%B3%B4%EA%B8%B0%EA%B4%80-%ED%99%94%EC%9B%A8%EC%9D%B4-%EC%A4%91%EA%B5%AD-%EC%A0%95%EB%B3%B4%EA%B8%B0%EA%B4%80%EC%97%90%EA%B2%8C-%EC%99%B8%EA%B5%AD-%EB%84%A4%ED%8A%B8/

**Comment by machenity** [comment]
https://www.clien.net/service/board/park/12960382
ITCle 서비스 종료되었습니다.
