### ISSUE TITLE
GitHub actions를 주기적으로 실행해서 테스트가 잘 도는지 확인하기

### ISSUE THREAD

**Issue by kanghyojun** [disjukr/just-news#352]
- just-news 특성상 뉴스 웹사이트에서 HTML의 구조 등을 변경하면 just-news의 기능에 버그가 생길 수 있습니다.
- 주기적으로 단위 테스트를 돌리면 이를 감지하여 뉴스 웹사이트 구조의 변경을 감지할 수 있으면 좋을 것 같습니다.

**Comment by disjukr** [comment]
related #326
