### ISSUE TITLE
health-check 테스트 케이스 추가하기

### ISSUE THREAD

**Issue by disjukr** [disjukr/just-news#370]
health-check는 주기적으로 돌아가는 테스트입니다.

이 테스트는 매일 돌면서 README 마지막의 지원현황을 갱신해줍니다.

테스트 케이스는 [이 곳](https://github.com/disjukr/just-news/blob/master/src/test/health-check/index.ts#L33)에 주변 테스트를 참고하여 추가하면 됩니다.

- [x] 경향신문
- [x] 국민일보
- [x] 나우뉴스
- [x] 네이버뉴스
- [x] 노컷뉴스
- [x] 뉴데일리
- [x] 뉴데일리경제
- [x] 뉴스1
- [x] 뉴시스
- [x] 다음뉴스
- [x] 데일리시큐
- [x] 데일리안
- [x] 데일리한국
- [x] 동아일보
- [x] 디스패치
- [x] 디지털데일리
- [x] 디지털타임스
- [x] 로이터
- [x] 마이데일리
- [x] 마이경제
- [x] 머니투데이
- [x] 문화일보
- [x] 미디어스
- [x] 미디어오늘
- [x] 민중의소리
- [x] 뷰스앤뉴스
- [x] 블로터닷넷
- [x] 서울경제
- [x] 서울신문
- [x] 세계일보
- [x] 스포츠경향
- [x] 스포츠동아
- [x] 스포츠서울
- [x] 스포츠조선
- [x] 스포탈코리아
- [x] 슬로우뉴스
- [x] 시사IN Live
- [x] 아시아경제
- [x] 아시아투데이
- [x] 아이뉴스24
- [x] 여성뉴스
- [x] 연합뉴스
- [x] 오마이뉴스
- [x] 월스트리트저널
- [x] 이데일리
- [x] 일간스포츠
- [x] 전자신문
- [x] 조선비즈
- [x] 조선일보
- [x] 중앙데일리
- [x] 중앙일보
- [x] 지디넷코리아
- [x] 지지통신
- [x] 코리아타임스
- [x] 코리아헤럴드
- [x] 파이낸셜뉴스
- [x] 프레시안
- [x] 한겨레
- [x] 한국경제
- [x] 한국경제증권
- [x] 한국경제TV
- [x] 한국일보
- [x] 허핑턴포스트
- [x] 헤럴드경제
- [x] ITWORLD
- [x] JTBC
- [x] JTBC-모바일
- [x] KBS World
- [x] KBS
- [x] MBC
- [x] MBN
- [x] OSEN
- [x] SBS
- [x] YTN

**Comment by tndus73** [comment]
최종수정본 추가하고 issues업데이트 부탁드립니다!

**Comment by disjukr** [comment]
관련 PR:
- https://github.com/disjukr/just-news/pull/402
- https://github.com/disjukr/just-news/pull/403
- https://github.com/disjukr/just-news/pull/404
- https://github.com/disjukr/just-news/pull/406
