### ISSUE TITLE
혹시 수집하는것에 대한 라이센스는 문제가 없나요??

### ISSUE THREAD

**Issue by YeoHoonYun** [disjukr/just-news#381]
제가 크롤링 프로그램을 만들때, 뉴스들은 거의 수집하면 안된다고만 하는데, 아닌가요??

**Comment by disjukr** [comment]
just-news의 코드를 이용해서 크롤러를 작성하시려는 것인가요?
저는 변리사가 아니라서 뉴스 수집을 통해 생기는 문제에 대해서 대답해드리기는 어려울 것 같습니다.

just-news 프로젝트 자체에 대한 질문이시라면, just-news는 뉴스 수집을 하지 않습니다.
just-news는 사용자 브라우저에서 직접 작동하기 때문에 뉴스를 수집하는 서버 등이 존재하지 않습니다.
