### ISSUE TITLE
YTN 작동하지 않음

### ISSUE THREAD

**Issue by youmin29** [disjukr/just-news#400]
현황 표에서 YTN에 녹색 체크 표시가 되어있길래 잘 작동하는 줄 알고 들어갔는데, YTN 뉴스를 들어가면 광고가 그대로 떠요....
확인 부탁드립니다!!

![ytn실행안됨](https://user-images.githubusercontent.com/84654372/142737023-0a5df81d-8088-4add-8a0e-3016b02f09c3.JPG)

**Comment by disjukr** [comment]
확인해보니 현황표 업데이트 봇은 1년 전에 죽었네요 ㅠㅠ

**Comment by disjukr** [comment]
고쳤습니다
